// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/ApplicantProfile.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace HumberGrpc {
  public static partial class Applicant
  {
    static readonly string __ServiceName = "ApplicantProfile.Applicant";

    static readonly grpc::Marshaller<global::HumberGrpc.Id> __Marshaller_ApplicantProfile_Id = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HumberGrpc.Id.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::HumberGrpc.ApplicantProfile> __Marshaller_ApplicantProfile_ApplicantProfile = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HumberGrpc.ApplicantProfile.Parser.ParseFrom);

    static readonly grpc::Method<global::HumberGrpc.Id, global::HumberGrpc.ApplicantProfile> __Method_GetApplicantProfile = new grpc::Method<global::HumberGrpc.Id, global::HumberGrpc.ApplicantProfile>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetApplicantProfile",
        __Marshaller_ApplicantProfile_Id,
        __Marshaller_ApplicantProfile_ApplicantProfile);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::HumberGrpc.ApplicantProfileReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Applicant</summary>
    [grpc::BindServiceMethod(typeof(Applicant), "BindService")]
    public abstract partial class ApplicantBase
    {
      public virtual global::System.Threading.Tasks.Task<global::HumberGrpc.ApplicantProfile> GetApplicantProfile(global::HumberGrpc.Id request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Applicant</summary>
    public partial class ApplicantClient : grpc::ClientBase<ApplicantClient>
    {
      /// <summary>Creates a new client for Applicant</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ApplicantClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Applicant that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ApplicantClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ApplicantClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ApplicantClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::HumberGrpc.ApplicantProfile GetApplicantProfile(global::HumberGrpc.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetApplicantProfile(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::HumberGrpc.ApplicantProfile GetApplicantProfile(global::HumberGrpc.Id request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetApplicantProfile, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::HumberGrpc.ApplicantProfile> GetApplicantProfileAsync(global::HumberGrpc.Id request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetApplicantProfileAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::HumberGrpc.ApplicantProfile> GetApplicantProfileAsync(global::HumberGrpc.Id request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetApplicantProfile, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ApplicantClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ApplicantClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ApplicantBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetApplicantProfile, serviceImpl.GetApplicantProfile).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ApplicantBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetApplicantProfile, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::HumberGrpc.Id, global::HumberGrpc.ApplicantProfile>(serviceImpl.GetApplicantProfile));
    }

  }
}
#endregion
